apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: web-1.0
spec:
  replicas: 2
  template:
    metadata:
      labels:
        name: web
        version: "1.0"
    spec:
      containers:
        - name: webapptest
          image: webapptest:1.0
          ports:
            - name: http
              containerPort: 80
